### ISSUE TITLE
System.DllNotFoundException on Linux

### ISSUE THREAD

**Issue by srid** [Zaid-Ajaj/desktop-feliz-with-photino#1]
On Linux (NixOS), the Desktop project fails to run:

```
❯ dotnet run
Suave server started
A Phontino window should pop up
That window is running the user interface hosted by webpack at http://localhost:3000
Meanwhile the (Suave) backend is running on http://localhost:5000
Webpack dev server will proxy all HTTP calls to Suave during the development session
Unhandled exception. [03:39:53 INF] Smooth! Suave listener started in 92.608ms with binding 127.0.0.1:5000
System.DllNotFoundException: Unable to load shared library 'Photino.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libPhotino.Native: cannot open shared object file: No such file or directory
   at PhotinoNET.PhotinoWindow.Photino_ctor(String title, IntPtr parentPhotinoNET, WebMessageReceivedDelegate webMessageReceivedCallback, Boolean fullscreen, Int32 x, Int32 y, Int32 width, Int32 height)
   at PhotinoNET.PhotinoWindow..ctor(String title, Action`1 configure, Int32 width, Int32 height, Int32 left, Int32 top, Boolean fullscreen)
   at Program.main(String[] args) in /home/srid/code/desktop-feliz-with-photino/Desktop/Program.fs:line 92
```

**Comment by Zaid-Ajaj** [comment]
Hi @srid, thanks for filing the issue. This is interesting. Seems like NixOS distribution isn't yet supported by Photino? 🤔 I will file an issue on the native Photino repo to track the problem and will keep you posted

**Comment by Zaid-Ajaj** [comment]
On Linux, Photino tries to use WebkitGTK+ which is assumed to be installed on your machine. Can you check that you have that dependency? Otherwise you can install it using 

sudo apt-get update && sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev

Though I am not sure this is the right dependency version

**Comment by srid** [comment]
Gotcha. On NixOS we would also have to tweak the LD variables.

**Comment by Zaid-Ajaj** [comment]
Did you manage to make it work for your distribution? 😄 Would be awesome to add a side-note of the extra requirements for Linux nixOS somewhere in the docs 🙏

**Comment by srid** [comment]
Not yet, but I'll open a PR when I get to that.
